project_id = "dznbihypzmvcmradijqn"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327

[auth]
enabled = true
port = 54328

[edge_functions]
enabled = true
port = 54329

[functions.create-driver]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.send-driver-credentials]
verify_jwt = true

[functions.mock-mechanics]
verify_jwt = false

[functions.emergency-reset]
verify_jwt = false

[functions.admin-password-reset]
verify_jwt = false

[functions.send-password-reset-notification]
verify_jwt = false

[functions.create-missing-auth-user]
verify_jwt = false

[functions.mobile-auth]
verify_jwt = false

[functions.create-payment]
verify_jwt = false

[functions.customer-portal]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true
