-- Insert sample customer profiles for testing
INSERT INTO public.customer_profiles (
  organization_id,
  customer_number,
  first_name,
  last_name,
  email,
  phone,
  date_of_birth,
  address_line_1,
  city,
  postal_code,
  country,
  emergency_contact_name,
  emergency_contact_phone,
  emergency_contact_relationship,
  customer_type,
  preferred_contact_method,
  loyalty_points,
  loyalty_tier,
  total_bookings,
  total_spent,
  average_rating,
  marketing_consent,
  data_protection_consent,
  terms_accepted,
  status,
  created_by
) 
SELECT 
  org.id,
  'CUST-2024-001',
  'Sarah',
  'Thompson',
  'sarah.thompson@email.com',
  '+44 20 7123 4567',
  '1985-03-15',
  '123 Oak Street',
  'London',
  'SW1A 1AA',
  'United Kingdom',
  'John Thompson',
  '+44 20 7123 4568',
  'Spouse',
  'individual',
  'email',
  150,
  'silver',
  12,
  2400.00,
  4.8,
  true,
  true,
  true,
  'active',
  prof.id
FROM public.organizations org
CROSS JOIN (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1) prof
LIMIT 1;

INSERT INTO public.customer_profiles (
  organization_id,
  customer_number,
  first_name,
  last_name,
  email,
  phone,
  address_line_1,
  city,
  postal_code,
  country,
  customer_type,
  company_name,
  company_registration_number,
  vat_number,
  preferred_contact_method,
  loyalty_points,
  loyalty_tier,
  total_bookings,
  total_spent,
  average_rating,
  marketing_consent,
  data_protection_consent,
  terms_accepted,
  status,
  created_by
) 
SELECT 
  org.id,
  'CUST-2024-002',
  'Michael',
  'Roberts',
  'michael.roberts@healthsolutions.co.uk',
  '+44 161 987 6543',
  '456 Medical Centre',
  'Manchester',
  'M1 2AB',
  'United Kingdom',
  'corporate',
  'Healthcare Solutions Ltd',
  '12345678',
  'GB123456789',
  'phone',
  75,
  'bronze',
  8,
  1800.00,
  4.6,
  true,
  true,
  true,
  'active',
  prof.id
FROM public.organizations org
CROSS JOIN (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1) prof
LIMIT 1;

-- Insert sample support tickets for testing
INSERT INTO public.support_tickets (
  organization_id,
  ticket_id,
  type,
  priority,
  subject,
  description,
  user_email,
  user_name,
  user_phone,
  app_version,
  device_info,
  status,
  assigned_to,
  resolution,
  tags,
  created_by
) 
SELECT 
  org.id,
  'TICKET-2024-001',
  'technical',
  'high',
  'Mobile app not loading on Samsung device',
  'The mobile app crashes immediately when opened on my Samsung Galaxy S21. I have tried reinstalling the app but the issue persists. Error message shows "Connection timeout".',
  'sarah.thompson@email.com',
  'Sarah Thompson',
  '+44 20 7123 4567',
  '2.1.0',
  'Samsung Galaxy S21, Android 13',
  'resolved',
  prof.id,
  'Issue was related to network configuration. Updated app to version 2.1.1 which includes improved error handling and network timeout settings.',
  ARRAY['mobile', 'android', 'crash']::TEXT[],
  prof.id
FROM public.organizations org
CROSS JOIN (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1) prof
LIMIT 1;

INSERT INTO public.support_tickets (
  organization_id,
  ticket_id,
  type,
  priority,
  subject,
  description,
  user_email,
  user_name,
  user_phone,
  app_version,
  device_info,
  status,
  tags,
  created_by
) 
SELECT 
  org.id,
  'TICKET-2024-002',
  'billing',
  'medium',
  'Invoice query for booking #BK-2024-015',
  'I received an invoice for booking #BK-2024-015 but there seems to be an additional charge that I do not understand. The invoice shows £45.00 but my booking confirmation showed £35.00. Can you please clarify this charge?',
  'michael.roberts@healthsolutions.co.uk',
  'Michael Roberts',
  '+44 161 987 6543',
  '2.1.0',
  'iPhone 14, iOS 17',
  'open',
  ARRAY['billing', 'invoice', 'dispute']::TEXT[],
  prof.id
FROM public.organizations org
CROSS JOIN (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1) prof
LIMIT 1;

-- Insert sample customer bookings for testing
INSERT INTO public.customer_bookings (
  organization_id,
  booking_number,
  customer_name,
  customer_email,
  customer_phone,
  pickup_location,
  dropoff_location,
  service_type,
  passengers,
  wheelchair_required,
  special_requirements,
  booking_date,
  pickup_time,
  dropoff_time,
  estimated_duration_minutes,
  estimated_distance_km,
  estimated_price,
  final_price,
  status,
  payment_status,
  payment_method,
  assigned_vehicle_id,
  assigned_driver_id,
  driver_notes,
  customer_rating,
  customer_feedback,
  created_by
) 
SELECT 
  org.id,
  'BK-2024-001',
  'Sarah Thompson',
  'sarah.thompson@email.com',
  '+44 20 7123 4567',
  '123 Oak Street, London, SW1A 1AA',
  'St. Thomas Hospital, Westminster Bridge Road, London, SE1 7EH',
  'medical_transport',
  1,
  false,
  'Patient has mild mobility issues, may need assistance getting in and out of vehicle',
  '2024-01-20',
  '09:00:00',
  '10:30:00',
  90,
  8.5,
  35.00,
  35.00,
  'completed',
  'paid',
  'card',
  v.id,
  driver.id,
  'Patient was on time and cooperative. No issues during transport.',
  5,
  'Excellent service! Driver was very helpful and professional. Will definitely use again.',
  prof.id
FROM public.organizations org
CROSS JOIN (SELECT id FROM public.vehicles LIMIT 1) v
CROSS JOIN (SELECT id FROM public.profiles WHERE role = 'driver' LIMIT 1) driver
CROSS JOIN (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1) prof
LIMIT 1;

INSERT INTO public.customer_bookings (
  organization_id,
  booking_number,
  customer_name,
  customer_email,
  customer_phone,
  pickup_location,
  dropoff_location,
  service_type,
  passengers,
  wheelchair_required,
  special_requirements,
  booking_date,
  pickup_time,
  dropoff_time,
  estimated_duration_minutes,
  estimated_distance_km,
  estimated_price,
  status,
  payment_status,
  created_by
) 
SELECT 
  org.id,
  'BK-2024-002',
  'Healthcare Solutions Ltd',
  'michael.roberts@healthsolutions.co.uk',
  '+44 161 987 6543',
  '456 Medical Centre, Manchester, M1 2AB',
  'Manchester Airport Terminal 1',
  'airport_transfer',
  3,
  true,
  'Wheelchair accessible vehicle required. Patient has limited mobility and requires assistance.',
  '2024-01-25',
  '14:00:00',
  '15:00:00',
  60,
  12.0,
  45.00,
  'confirmed',
  'pending',
  prof.id
FROM public.organizations org
CROSS JOIN (SELECT id FROM public.profiles WHERE role = 'admin' LIMIT 1) prof
LIMIT 1;
